opensquare-network/collaboration

components/account.js, components/header.js
=> feature: absolute position for mobile pop-uo header menu

components/header.js
=> fix: header responsive issue

components/home.js, components/post.js, components/postList.js, pages/index.js
=> Add space tag

components/ellipsis.js, components/flex.js, components/postDetail/postVote.js, components/postDetail/postVotes.js
=> refs#132 new option choice layout

components/postCreate/index.js, utils/viewfunc.js
=> refs#114 add formvalidation before request the create proposal API #114

components/space.js
=> fix: show space item box-shadow

components/button.js, components/postCreate/more.js
=> refs #227 change button font style to 14px 500

components/account.js
=> fix: refs #260 account & menu

utils/index.js, utils/index.test.js
=> fix frontend tests

utils/index.js, utils/index.test.js
=> fix： moment relavent tests

packages/next/components/postDetail/postVotes.js, packages/next/frontedUtils/hooks.js
=> Update my vote

packages/next/components/postCreate/more.js, packages/next/components/row.js, packages/next/components/tooltip/index.js, packages/next/frontedUtils/index.js
=> fix: abbr balance display incase its long text

packages/next/components/account.js, packages/next/components/author.js, packages/next/components/identityIcon.js, packages/next/components/tooltip.js
=> Add tooltip to identity

packages/next/components/postAddress.js, packages/next/components/postCreate/index.js, packages/next/components/postCreate/information.js, packages/next/components/postCreate/more.js
=> Fix ui 1208

packages/next/components/postDetail/postTab.js
=> fix: correct error about plural

packages/next/components/postAddress.js, packages/next/components/postCreate/index.js
https://user-images.githubusercontent.com/12393771/151645780-70c940a9-fa89-4a43-b927-5e885aa199b8.mov
=> hotfix: exception thrown while inputing address

packages/next/components/space.js, packages/next/public/imgs/icons/plus.svg
=> feature: implement "Add a Space" button #439

package.json, packages/next/components/account.js, packages/next/components/chainSelector.js, packages/next/components/connect.js, yarn.lock
=> hide <Connect> for home, and show relavant chains in modal,  #487

packages/next/components/postCreate/more.js
=> UI fix margin #546

packages/next/components/accountSelector.js, packages/next/components/chain/chainIcon.js, packages/next/components/chainSelector.js
=> Multi chain fix ui3

packages/next/components/account.js, packages/next/components/postDetail/postContent.js, packages/next/components/postDetail/postDiscussion.js
=> bugfix: <Author> network un-shown & identity status icon incorrect

packages/next/components/space.js
=> UI: display total proposal count on spaces page, #622

packages/next/components/author.js, packages/next/components/chain/chainIcon.js, packages/next/components/listInfo.js
=> feat(next): tooltip network name

packages/next/components/postDetail/biasedVotingItem.js, packages/next/components/postDetail/postResults.js
=> fix(next): one line voting display

packages/next/components/postCreate/more.js
=> improve: display "-" for unknown-snapshot height network, #685

packages/next/next.config.js
=> to use svg importation in @osn/common-ui

packages/next/next.config.js
Reverts opensquare-network/collaboration#689
=> Revert "to use svg importation in @osn/common-ui"

packages/next/components/connect/connectButton/index.js
=> fix(next): button import

packages/next/components/option.js
=> style: fix vote button index position ,#695

packages/next/package.json, yarn.lock
fix https://github.com/opensquare-network/collaboration/security/dependabot/15
=> update dependency to resolve Dependabot alerts

packages/next/components/postDetail/postDiscussion.js, packages/next/components/postDetail/postVotes.js
=> refactor(next): use nodata

packages/next/components/flex.js, packages/next/components/postDetail/postVotesItem.js, packages/next/components/role/voter.js, packages/next/components/sideBar/sideSectionTitle.js
=> refactor(next): common ui flex

packages/next/components/postDetail/postContent.js, packages/next/components/sideBar/sideSectionTitle.js, packages/next/components/snapshotHeightPicker.js, packages/next/components/styled/flex.js, packages/next/components/styled/subTitle.js
=> refactor(next): common ui subtitle

packages/next/components/chainSelector.js
=> refactor(next): common ui dropdown selector

packages/next/components/postDetail/postContent.js, packages/next/components/postDetail/postDiscussion.js, packages/next/package.json, yarn.lock
close #713 
~~dynamic because the preview/micromark uses the browser api.~~
=> refactor(next): common ui preview

packages/next/components/connect/closeable.js, packages/next/package.json, yarn.lock
=> refactor(next): common ui modal for `closeable.js`

packages/next/components/statusTag.js
=> refactor(next): common ui tag

packages/next/pages/_app.js
https://github.com/opensquare-network/paid-qa/pull/496
=> refactor(next): import react-mde css

packages/next/components/header.js
=> fix(next): header logo cursor

packages/next/components/option.js
=> fix(next): option disabled color

packages/next/components/account.js, packages/next/components/author.js, packages/next/components/identityOrAddr.js, packages/next/components/role/voter.js, packages/next/services/nextApi.js
=> bugfix: show full identity in popup, #612

packages/next/components/connect/connectButton/index.js, packages/next/components/option.js, packages/next/components/postCreate/choices.js, packages/next/components/postCreate/publish.js, packages/next/components/postDetail/postVote.js, packages/next/package.json, yarn.lock
=> refactor(next): new button

packages/next/components/postCreate/content.js, packages/next/package.json, yarn.lock
https://github.com/opensquare-network/paid-qa/pull/511
should update to 0051
=> refactor(next): common ui rich editor button

packages/next/components/identityOrAddr.js, packages/next/components/postDetail/postVotesItem.js, packages/next/components/role/voter.js
=> HOTFIX: improve post vote item layout, #756

packages/next/package.json, yarn.lock
=> chore(next): deps common ui

package.json, packages/next/package.json, packages/next/patches/@osn+common-ui+0.0.57.patch, yarn.lock
=> HOTFIX: temporary solution, use a patch to fix icon isssue

packages/next/components/author.js, packages/next/components/identityOrAddr.js
=> fix(next): fix identity icon size

packages/next/components/main.js, packages/next/pages/404.js
=> fix(next): header border bottom

packages/next/next.config.js, packages/next/package.json, yarn.lock
=> chore(next): upgrade editor to `0019`

packages/next/components/option.js
=> style vote option button padding #795

packages/next/components/postDetail/postVote.js, packages/next/components/postDetail/terminate.js, packages/next/frontedUtils/viewfunc.js
=> feat(next): terminate proposal

packages/next/package.json, yarn.lock
=> chore: bump editor v0.1.14

packages/next/components/postCreate/content.js, packages/next/components/postDetail/postDiscussion.js, packages/next/package.json, yarn.lock
=> feat: use new editor

packages/next/components/account.js, packages/next/components/header.js, packages/next/components/layout.js, packages/next/components/shade.js
=> header: new mobile menu shade

packages/next/package.json, yarn.lock
=> chore(deps): upgrade common ui

packages/next/components/option.js, packages/next/components/postDetail/postVotesItem.js
=> Hotfix responsive

packages/next/components/postDetail/postVotes.js, packages/next/components/postDetail/postVotesItem.js
=> style:show choice index only for mobile

packages/next/components/author.js, packages/next/components/postDetail/postDiscussion.js, packages/next/components/postDetail/suggestions.js
=> feat(next): mention

packages/next/components/postDetail/postDiscussion.js, packages/next/next.config.js, packages/next/package.json, yarn.lock
=> feat: mention identity user

packages/next/components/postCreate/content.js, packages/next/components/postDetail/appendants.js, packages/next/components/postDetail/postDiscussion.js, packages/next/package.json, yarn.lock
https://github.com/opensquare-network/paid-qa/pull/743
=> fix(next): ssr rich editor

next/components/header.js, next/public/imgs/icons/apps-color.svg, next/public/imgs/icons/caret-right-s.svg, next/public/imgs/icons/short-term-employment.svg, next/public/imgs/icons/voting.svg
=> feat: header navi menu  (add bounty)

next/package.json, next/yarn.lock
=> chore(deps): ui

backend/packages/backend/src/features/spaces/createSpace.js
=> fix: allow hyphens in new space name

next/components/account.js, next/components/header.js
=> fix: switch address popup

next/components/space.js, next/components/spaceListItem/index.js
=> fix: space item responsive layout

next/pages/space/[space]/proposal/[id].js, next/store/reducers/accountSlice.js
=> Update cookie version, #1112
